__author__ = "Soumit Salman Rahman"
__license__ = "MIT"
__version__ = "1.0.2"

from .apicollectors import (
    APICollectorBase,
    RSSFeedCollector,
    GovInfoRSSCollector,
    RedditCollector,
    HackerNewsCollector,
    SECFilingCollector,
    REDDIT,
    HACKERNEWS,
    HACKERNEWS_STORIES_URLS,
)
from .scrapers import WebCrawler, AsyncWebScraper
from .settings import MAX_HTML_SIZE, MAX_PDF_SIZE, TIMEOUT
from .normalize import (
    POST,
    BLOG,
    NEWS,
    SITE,
    PODCAST,
    CONTRACT,
    PROCUREMENT_NOTICE,
    FINANCIAL_REPORT,
    EARNINGS_REPORT,
    SEC_FILING,
    PRESS_RELEASE,
    OFFICIAL_STATEMENT,
    ENFORCEMENT_ACTION,
    LEGISLATIVE_BILL,
    LEGISLATIVE_PROPOSAL,
    ENACTED_LAW,
    REGULATION,
    RULEMAKING_NOTICE,
    COURT_OPINION,
    LAWSUIT,
    GOVERNMENT_REPORT,
    BUDGET_DOCUMENT,
    LEGISLATIVE_RECORD,
    HEARING,
    RESEARCH_PAPER,
    WHITEPAPER,
    TECHNICAL_DOCUMENTATION,
    ContentGate,
    is_excluded_content,
    excluded_url,
    cleanup_item,
    guess_content_type,
)

__all__ = [
    "APICollectorBase",
    "RSSFeedCollector",
    "GovInfoRSSCollector",
    "RedditCollector",
    "HackerNewsCollector",
    "SECFilingCollector",
    "WebCrawler",
    "AsyncWebScraper",
    "REDDIT",
    "HACKERNEWS",
    "HACKERNEWS_STORIES_URLS",
    "POST",
    "BLOG",
    "NEWS",
    "SITE",
    "PODCAST",
    "CONTRACT",
    "PROCUREMENT_NOTICE",
    "FINANCIAL_REPORT",
    "EARNINGS_REPORT",
    "SEC_FILING",
    "PRESS_RELEASE",
    "OFFICIAL_STATEMENT",
    "ENFORCEMENT_ACTION",
    "LEGISLATIVE_BILL",
    "LEGISLATIVE_PROPOSAL",
    "ENACTED_LAW",
    "REGULATION",
    "RULEMAKING_NOTICE",
    "COURT_OPINION",
    "LAWSUIT",
    "GOVERNMENT_REPORT",
    "BUDGET_DOCUMENT",
    "LEGISLATIVE_RECORD",
    "HEARING",
    "RESEARCH_PAPER",
    "WHITEPAPER",
    "TECHNICAL_DOCUMENTATION",
    "ContentGate",
    "is_excluded_content",
    "excluded_url",
    "cleanup_item",
    "guess_content_type",
    "MAX_HTML_SIZE",
    "MAX_PDF_SIZE",
    "TIMEOUT",
]
