version: '3.8'

services:
  localcollector:
    image: soumitsr/coffeemaker:06-04
    depends_on:
      - localcrawler
      - localdb
    environment:
      - MODE=COLLECTOR
      - DB_NAME=test
      - MONGODB_CONN_STR=mongodb://localdb:27017
      - REMOTE_CRAWLER_URL=http://localcrawler:11235
      - BATCH_SIZE=64
    env_file:
      - dockertest.env
    networks:
      - coffeemaker-bridge
    cpus: 1
    mem_limit: 1g

  localindexer:
    image: soumitsr/coffeemaker:06-05
    depends_on:
      - localdb
    environment:
      - MODE=INDEXER
      - DB_NAME=test
      - MONGODB_CONN_STR=mongodb://localdb:27017
      - BATCH_SIZE=64
      - MAX_RELATED_EPS=0.1
    env_file:
      - dockertest.env
    networks:
      - coffeemaker-bridge
    cpus: 2
    mem_limit: 4g

  localdigestor:
    image: soumitsr/coffeemaker:06-04
    depends_on:
      - localdb
    environment:
      - MODE=DIGESTOR
      - DB_NAME=test
      - MONGODB_CONN_STR=mongodb://localdb:27017
      - BATCH_SIZE=64
    env_file:
      - dockertest.env
    networks:
      - coffeemaker-bridge
    cpus: 1
    mem_limit: 1g

  localcomposer:
    image: soumitsr/coffeemaker:06-04
    depends_on:
      - localdb
      - azurite
    environment:
      - MODE=COMPOSER
      - DB_NAME=test
      - MONGODB_CONN_STR=mongodb://localdb:27017
      - AZSTORAGE_CONN_STR=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://azurite:10001/devstoreaccount1;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - MIN_CLUSTER_SIZE=24
      - MAX_ARTICLES=2
    env_file:
      - dockertest.env
    networks:
      - coffeemaker-bridge

  localcrawler:
    image: unclecode/crawl4ai:latest
    ports:
      - "11235:11235"
    networks:
      - coffeemaker-bridge
    cpus: 1
    mem_limit: 1g

  localdb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    networks:
      - coffeemaker-bridge
    cpus: 1
    mem_limit: 4g

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - "10000:10000"
      - "10001:10001"
    command: azurite-blob --blobHost 0.0.0.0 
    networks:
      - coffeemaker-bridge
    cpus: 1
    mem_limit: 1g

networks:
  coffeemaker-bridge:
    driver: bridge
