version: '3.8'

services:
  localcollector:
    image: soumitsr/coffeemaker:05-27
    depends_on:
      - localcrawler
      - localdb
      - localqueue
    environment:
      - MODE=COLLECTOR_ONLY
      - DB_NAME=test
      - MONGODB_CONN_STR=mongodb://localdb:27017
      - REMOTE_CRAWLER_URL=http://localcrawler:11235
      - AZQUEUE_CONN_STR=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://localqueue:10001/devstoreaccount1;
      - OUTPUT_QUEUE_NAMES=indexing-queue,digesting-queue
      - BATCH_SIZE=64
    env_file:
      - dockertest.env
    networks:
      - coffeemaker-bridge

  localindexer:
    image: soumitsr/coffeemaker:05-24
    depends_on:
      - localdb
      - localqueue
    environment:
      - MODE=INDEXER_ONLY
      - DB_NAME=test
      - MONGODB_CONN_STR=mongodb://localdb:27017
      - AZQUEUE_CONN_STR=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://localqueue:10001/devstoreaccount1;
      - INPUT_QUEUE_NAME=indexing-queue
      - BATCH_SIZE=64
    env_file:
      - dockertest.env
    networks:
      - coffeemaker-bridge

  localdigestor:
    image: soumitsr/coffeemaker:05-24
    depends_on:
      - localdb
      - localqueue
    environment:
      - MODE=DIGESTOR_ONLY
      - DB_NAME=test
      - MONGODB_CONN_STR=mongodb://localdb:27017
      - AZQUEUE_CONN_STR=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://localqueue:10001/devstoreaccount1;
      - INPUT_QUEUE_NAME=digesting-queue
      - BATCH_SIZE=16
    env_file:
      - dockertest.env
    networks:
      - coffeemaker-bridge

  localcrawler:
    image: unclecode/crawl4ai:latest
    ports:
      - "11235:11235"
    networks:
      - coffeemaker-bridge

  localqueue:
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite-queue --queueHost 0.0.0.0 
    ports:
      - "10001:10001"
    networks:
      - coffeemaker-bridge

  localdb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    networks:
      - coffeemaker-bridge

networks:
  coffeemaker-bridge:
    driver: bridge
