version: '3.8'

services:
  localcollector:
    image: soumitsr/coffeemaker:05-30
    depends_on:
      - localcrawler
      - localdb
    environment:
      - MODE=COLLECTOR
      - DB_NAME=test
      - MONGODB_CONN_STR=mongodb://localdb:27017
      - REMOTE_CRAWLER_URL=http://localcrawler:11235
      - AZQUEUE_CONN_STR=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://localqueue:10001/devstoreaccount1;
      - OUTPUT_QUEUE_NAMES=indexing-queue,digesting-queue
      - BATCH_SIZE=64
    env_file:
      - dockertest.env
    networks:
      - coffeemaker-bridge
    cpus: 1
    mem_limit: 1g

  localindexer:
    image: soumitsr/coffeemaker:05-30
    depends_on:
      - localdb
    environment:
      - MODE=INDEXER
      - DB_NAME=test
      - MONGODB_CONN_STR=mongodb://localdb:27017
      - BATCH_SIZE=64
    env_file:
      - dockertest.env
    networks:
      - coffeemaker-bridge
    cpus: 2
    mem_limit: 4g

  localdigestor:
    image: soumitsr/coffeemaker:05-30
    depends_on:
      - localdb
    environment:
      - MODE=DIGESTOR
      - DB_NAME=test
      - MONGODB_CONN_STR=mongodb://localdb:27017
      - AZQUEUE_CONN_STR=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://localqueue:10001/devstoreaccount1;
      - INPUT_QUEUE_NAME=digesting-queue
      - BATCH_SIZE=8
    env_file:
      - dockertest.env
    networks:
      - coffeemaker-bridge
    cpus: 1
    mem_limit: 1g

  localcomposer:
    image: soumitsr/coffeemaker:05-30
    depends_on:
      - localdb
    environment:
      - MODE=DIGESTOR
      - DB_NAME=test
      - MONGODB_CONN_STR=mongodb://localdb:27017
      - AZQUEUE_CONN_STR=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://localqueue:10001/devstoreaccount1;
      - INPUT_QUEUE_NAME=digesting-queue
      - BATCH_SIZE=8
    env_file:
      - dockertest.env
    networks:
      - coffeemaker-bridge

  localcrawler:
    image: unclecode/crawl4ai:latest
    ports:
      - "11235:11235"
    networks:
      - coffeemaker-bridge
    cpus: 1
    mem_limit: 1g

  localdb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    networks:
      - coffeemaker-bridge
    cpus: 1
    mem_limit: 4g

networks:
  coffeemaker-bridge:
    driver: bridge
