version: '3.8'

services:
  localcollector:
    image: soumitsr/coffeemaker:06-25
    depends_on:
      - localdb
    environment:      
      - DB_NAME=20250625
      - MONGODB_CONN_STR=mongodb://localdb:27017
      - MODE=COLLECTOR
      - BATCH_SIZE=32
    env_file:
      - dockertest.env
    networks:
      - coffeemaker-bridge
    cpus: 1
    mem_limit: 1g

  localindexer:
    image: soumitsr/coffeemaker:06-25-1
    depends_on:
      - localdb
    environment:
      - DB_NAME=20250625
      - MONGODB_CONN_STR=mongodb://localdb:27017
      - MODE=INDEXER
      - BATCH_SIZE=64
    env_file:
      - dockertest.env
    networks:
      - coffeemaker-bridge
    cpus: 3
    mem_limit: 5g

  localdigestor:
    image: soumitsr/coffeemaker:gpu-06-25
    depends_on:
      - localdb
      - azurite
    environment:
      - DB_NAME=20250625
      - MONGODB_CONN_STR=mongodb://localdb:27017
      - AZSTORAGE_CONN_STR=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://azurite:10001/devstoreaccount1;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - MODE=DIGESTOR
      - BATCH_SIZE=4
    env_file:
      - dockertest.env
    networks:
      - coffeemaker-bridge
    cpus: 3
    mem_limit: 6g
    

  localcomposer:
    image: soumitsr/coffeemaker:06-25
    depends_on:
      - localdb
      - azurite
    environment:      
      - DB_NAME=20250623
      - MONGODB_CONN_STR=mongodb://localdb:27017
      - AZSTORAGE_CONN_STR=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://azurite:10001/devstoreaccount1;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - MIN_CLUSTER_SIZE=24
      - MAX_CLUSTER_SIZE=64
      - MAX_ARTICLES=2
    command: --mode COMPOSER
    env_file:
      - dockertest.env
    networks:
      - coffeemaker-bridge

  localcrawler:
    image: unclecode/crawl4ai:latest
    ports:
      - "11235:11235"
    networks:
      - coffeemaker-bridge
    cpus: 1
    mem_limit: 1g

  localdb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    networks:
      - coffeemaker-bridge
    cpus: 1
    mem_limit: 4g

  localpostgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=doadmin
      - POSTGRES_PASSWORD=eatabagofdicks
      - POSTGRES_DB=test_beansackdb0
    networks:
      - coffeemaker-bridge
    cpus: 1
    mem_limit: 1g

  localn8n:
    image: n8nio/n8n:latest
    environment:
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_AVAILABLE_BINARY_DATA_MODES=filesystem
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    ports:
      - "5678:5678"
    volumes:
      - .n8n:/home/node/.n8n
      - .postgresql:/certs

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - "10000:10000"
      - "10001:10001"
    command: azurite-blob --blobHost 0.0.0.0 
    networks:
      - coffeemaker-bridge
    cpus: 1
    mem_limit: 1g

networks:
  coffeemaker-bridge:
    driver: bridge
