# fly.toml app configuration file generated for coffeemaker-collector-job on 2026-07-27T12:48:18-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'coffeemaker-collector-job'
primary_region = 'iad'

[build]
  dockerfile = 'DockerfileIO'
  ignorefile = '.dockerignore'

[env]
  BATCH_SIZE = '24'
  MODE = 'COLLECTOR'
  COLLECTOR_TIMEOUT = '180'
  PG_WORKERS = '8'
  PROCESSING_WINDOW = '2'

[[restart]]
  policy = 'never'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '2048mb'
