app = "pycoffeemaker"
primary_region = "ord"

# Define all the processes
[processes]
collector = "python ./run.py --mode COLLECTOR --batch_size 64"
composer = "python ./run.py --mode COMPOSER --max_articles 8"
# indexer = "python ./run.py --mode INDEXER --batch_size 128"
# digestor = "python ./run.py --mode DIGESTOR --batch_size 48"

# VM configuration for CPU-based processes (collector and composer)
[[vm]]
cpu_kind = "shared"
memory = "1gb"
size = "shared-cpu-1x"
processes = ["collector", "composer"]

# VM configuration for GPU-based processes (indexer and digestor)
# [[vm]]
# cpu_kind = "performance"
# memory = "32gb"
# size = "l40s"
# gpu_kind = "l40s"
# processes = ["indexer", "digestor"]

[[services]]
auto_stop_machines = "stop"
auto_start_machines = false
min_machines_running = 0
processes = ["collector", "composer"]

[[restart]]
policy = "never"
retries = 0
processes = ["collector", "composer"]

[env]
PYTORCH_CUDA_ALLOC_CONF = "expandable_segments:True"
